name = "test"
title = "Test layout"

[auto_activation]
window_title = "Notepad|Ghrome"

[rules]
"[]CAPS_LOCK↓" = "LEFT_WIN↓ → SPACE↓ → SPACE↑ → LEFT_WIN↑"
"[LEFT_SHIFT] CAPS_LOCK↓" = "CAPS_LOCK↓ → CAPS_LOCK↑"
