name = "invert_mouse"
title = "Mouse invert"

[rules]
#"MOUSE_Y*" = "MOUSE_Y^"
#"MOUSE_Y^" = "MOUSE_Y*"

#"WHEEL_Y*" = "WHEEL_Y^"
#"WHEEL_Y^" = "WHEEL_Y*"

#"WHEEL_Y*" = "D* > D^"
#"WHEEL_Y^" = "U* > U^"

"XBUTTON1" = "A"
#"A" = "XBUTTON1"
#"XBUTTON2" = "B"
#"B" = "XBUTTON2"

#"LEFT_BUTTON" = "1"
#"RIGHT_BUTTON" = "2"
#"MIDDLE_BUTTON" = "3"
#"1" = "LEFT_BUTTON"
#"2" = "RIGHT_BUTTON"
#"3" = "MIDDLE_BUTTON"