[strings]
app_title = "Keympostor"
clear_log = "Clear log"
enabled = "Enabled"
exit = "Exit"
file = "File"
log = "Log"
logging_enabled = "Logging enabled"
open = "Open"
layout = "Layout"
no_layout = "No layout"
no_profile = "No profile"
tray_tip = "Keympostor"
action = "Action"
rule = "Rule"
modifiers = "Modifiers"
transition = "Transition"
auto_switch_layout = "Auto switch layout"
key = "Key"
status = "Status"
time = "Time"
virtual_key = "Virtual key"
scan_code = "Scan code"

[sounds]
switch_profile="res\\sound\\clack.wav"