[[profile]]
name = "default"
title = "Default profile"

[[profile]]
name = "game"
title = "Game profile"

[[profile.rules]]
"INSERT" = "ESC"
"LAUNCH_APP2, FN_LAUNCH_APP2" = "F3"
"BROWSER_SEARCH" = "F4"
"[]BACKSPACE" = "F5"
"NUM_LOCK" = "1"
"NUM_DIV" = "2"
"NUM_MUL" = "3"
"NUM_MINUS" = "4"
"NUM_7, NUM_HOME" = "Q"
"NUM_8, NUM_UP" = "W"
"NUM_9, NUM_PAGE_UP" = "E"
"NUM_PLUS" = "TAB"
"NUM_4, NUM_LEFT" = "A"
"NUM_5, NUM_CLEAR" = "S"
"NUM_6, NUM_RIGHT" = "D"
"NUM_1, NUM_END" = "F"
"NUM_2, NUM_DOWN" = "T"
"NUM_3, NUM_PAGE_DOWN" = "R"
"NUM_ENTER" = "SPACE"
"NUM_0, NUM_INSERT" = "M"
"NUM_DOT, NUM_DELETE" = "LEFT_SHIFT"