processing_enabled = true
logging_enabled = true
layouts_enabled = false
layout = "default"

[main_window]
position = [822, 138]
size = [977, 560]
selected_page = 0

[log_view.columns]
3 = 50
5 = 50
6 = 108
2 = 89
4 = 50
8 = 50
1 = 179
7 = 94
0 = 187
