logging_enabled = true
profiles_enabled = true
transform_layout = "default"
toggle_layout_hot_key = "[] F1â†‘"

[main_window]
position = [983, 147]
size = [716, 428]
selected_page = 1

[main_window.log_view.columns]
8 = 50
2 = 50
6 = 50
7 = 50
4 = 50
0 = 300
5 = 50
1 = 500
3 = 50
