logging_enabled = true
profiles_enabled = true
transform_layout = "game"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[main_window]
position = [335, 147]
size = [1364, 428]
selected_page = 0

[main_window.log_view.columns]
5 = 81
0 = 300
4 = 73
6 = 64
3 = 79
8 = 50
2 = 77
1 = 500
7 = 50
