logging_enabled = true
profiles_enabled = true
transform_layout = "default"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[main_window]
position = [571, 286]
size = [1364, 428]
selected_page = 0

[main_window.log_view.columns]
2 = 77
1 = 500
4 = 73
6 = 64
0 = 300
7 = 50
3 = 79
5 = 81
8 = 50
