processing_enabled = true
logging_enabled = true
layouts_enabled = false
layout = "game"

[main_window]
position = [822, 138]
size = [977, 560]
selected_page = 1

[log_view.columns]
6 = 108
2 = 89
3 = 50
5 = 50
8 = 50
0 = 187
4 = 50
1 = 179
7 = 94
