processing_enabled = true
logging_enabled = true
window_profile_enabled = true
profile = "game"

[main_window]
position = [1191, 71]
size = [793, 339]
selected_page = 0

[[window_profile]]
rule = "Chrome"
profile = "game"

[[window_profile]]
rule = "TOTALCMD64.EXE"
profile = "game"
