logging_enabled = true
profiles_enabled = true
transform_layout = "default"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[main_window]
position = [335, 147]
size = [1364, 428]
selected_page = 1

[main_window.log_view.columns]
7 = 50
3 = 79
6 = 64
8 = 50
1 = 500
2 = 77
0 = 300
4 = 73
5 = 81
