processing_enabled = false
logging_enabled = true
window_profile_enabled = true
profile = "default"

[main_window]
position = [1268, 71]
size = [716, 339]
selected_page = 0

[[window_profile]]
rule = "Chrome"
profile = "game"

[[window_profile]]
rule = "TOTALCMD64.EXE"
profile = "game"
