keys_logging_enabled = true
last_transform_layout = "default"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[layout_autoswitch]
enabled = false

[layout_autoswitch.profiles.tc]
activation_rule = "TOTALCMD64.EXE"
transform_layout = "ide"

[layout_autoswitch.profiles.ide]
activation_rule = "rustrover64.exe"
transform_layout = "default"

[layout_autoswitch.profiles.chrome]
activation_rule = "Chrome"
transform_layout = "default"

[main_window]
position = [340, 237]
size = [1534, 504]
selected_page = 0

[main_window.log_view.columns]
0 = 284
3 = 185
7 = 50
8 = 50
6 = 131
2 = 107
5 = 116
1 = 254
4 = 91
