logging_enabled = true
profiles_enabled = false
transform_layout = "game"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[main_window]
position = [396, 273]
size = [1475, 428]
selected_page = 0

[main_window.log_view.columns]
3 = 79
4 = 73
1 = 500
2 = 77
7 = 69
8 = 50
0 = 300
5 = 95
6 = 96
