processing_enabled = true
logging_enabled = true
layouts_enabled = false
layout = "invert_mouse"

[main_window]
position = [811, 298]
size = [716, 536]
selected_page = 1

[profiles.chrome]
rule = "Chrome"
layout = "game"

[profiles.totalcmd]
rule = "TOTALCMD64.EXE"
layout = "game"
