keys_logging_enabled = true
last_transform_layout = "ide"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†“"

[layout_autoswitch]
enabled = true

[layout_autoswitch.profiles.tc]
activation_rule = "TOTALCMD64.EXE"
transform_layout = "game"

[layout_autoswitch.profiles.chrome]
activation_rule = "Chrome"
transform_layout = "default"

[layout_autoswitch.profiles.ide]
activation_rule = "rustrover64.exe"
transform_layout = "ide"

[main_window]
position = [261, 204]
size = [1534, 504]
selected_page = 0

[main_window.log_view.columns]
2 = 211
5 = 116
3 = 50
8 = 50
6 = 131
4 = 91
0 = 300
1 = 254
7 = 50
