logging_enabled = true
profiles_enabled = true
transform_layout = "game"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[main_window]
position = [608, 232]
size = [716, 428]
selected_page = 0

[main_window.log_view.columns]
5 = 50
6 = 50
4 = 50
1 = 500
0 = 300
3 = 50
2 = 50
7 = 50
8 = 50
