logging_enabled = true
profiles_enabled = true
transform_layout = "default"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[main_window]
position = [571, 286]
size = [1364, 428]
selected_page = 0

[main_window.log_view.columns]
3 = 79
0 = 300
5 = 81
1 = 500
2 = 77
4 = 73
8 = 50
6 = 64
7 = 50
