processing_enabled = true
logging_enabled = true
layouts_enabled = false
layout = "invert_mouse"

[main_window]
position = [822, 138]
size = [716, 560]
selected_page = 0

[log_view.columns]
2 = 65
0 = 129
1 = 211
5 = 50
8 = 50
4 = 50
6 = 108
3 = 50
7 = 94
