logging_enabled = true
profiles_enabled = true
transform_layout = "game"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[main_window]
position = [396, 273]
size = [1475, 428]
selected_page = 0

[main_window.log_view.columns]
2 = 77
3 = 79
0 = 300
6 = 96
1 = 500
4 = 73
7 = 69
5 = 95
8 = 50
