logging_enabled = true
profiles_enabled = true
transform_layout = "default"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[main_window]
position = [335, 147]
size = [1364, 428]
selected_page = 1

[main_window.log_view.columns]
5 = 81
3 = 79
0 = 300
1 = 500
2 = 77
6 = 64
4 = 73
8 = 50
7 = 50
