processing_enabled = true
logging_enabled = false
layouts_enabled = false
layout = "game"

[main_window]
position = [822, 138]
size = [977, 560]
selected_page = 0

[log_view.columns]
3 = 50
6 = 108
8 = 50
5 = 50
4 = 50
2 = 89
1 = 179
7 = 94
0 = 187
