processing_enabled = true
logging_enabled = true
layouts_enabled = false
layout = "default"

[main_window]
position = [822, 138]
size = [716, 560]
selected_page = 0

[log_view.columns]
1 = 94
3 = 50
2 = 50
4 = 50
7 = 94
6 = 50
5 = 50
0 = 124
8 = 50
