processing_enabled = true
logging_enabled = true
layouts_enabled = false
layout = "default"

[main_window]
position = [822, 138]
size = [716, 560]
selected_page = 0

[log_view.columns]
3 = 50
5 = 50
4 = 50
0 = 129
6 = 108
8 = 50
7 = 94
2 = 89
1 = 179
