logging_enabled = true
profiles_enabled = true
transform_layout = "default"

[main_window]
position = [566, 209]
size = [716, 475]
selected_page = 1

[main_window.log_view.columns]
2 = 50
0 = 300
4 = 50
6 = 50
1 = 500
5 = 50
8 = 50
7 = 50
3 = 50
