processing_enabled = false
logging_enabled = false
layouts_enabled = false
layout = "default"

[main_window]
position = [300, 300]
size = [716, 339]
selected_page = 0

[[profiles]]
rule = "Chrome"
layout = "game"

[[profiles]]
rule = "TOTALCMD64.EXE"
layout = "game"
