processing_enabled = true
logging_enabled = true
layouts_enabled = true
layout = "default"

[main_window]
position = [1268, 165]
size = [716, 550]
selected_page = 1

[[profiles]]
name = "tc"
rule = "TOTALCMD64.EXE"
layout = "default"

[[profiles]]
name = "chrome"
rule = "Chrome"
layout = "game"
