processing_enabled = true
logging_enabled = true
layouts_enabled = false
layout = "default"

[main_window]
position = [822, 138]
size = [716, 560]
selected_page = 0

[log_view.columns]
1 = 179
2 = 89
4 = 50
0 = 129
8 = 50
3 = 50
5 = 50
6 = 108
7 = 94
