processing_enabled = true
logging_enabled = true
layouts_enabled = false
layout = "game"

[main_window]
position = [782, 128]
size = [716, 573]
selected_page = 0

[profiles.totalcmd]
rule = "TOTALCMD64.EXE"
layout = "game"

[profiles.chrome]
rule = "Chrome"
layout = "game"
