logging_enabled = false
layouts_enabled = true
layout = "game"

[main_window]
position = [822, 138]
size = [977, 560]
selected_page = 0

[log_view.columns]
4 = 50
1 = 179
2 = 89
7 = 94
5 = 50
3 = 50
6 = 108
0 = 187
8 = 50
