logging_enabled = false
layouts_enabled = false

[main_window]
position = [822, 138]
size = [977, 560]
selected_page = 0

[log_view.columns]
2 = 89
5 = 50
6 = 108
8 = 50
1 = 179
7 = 94
0 = 187
3 = 50
4 = 50
