logging_enabled = true
profiles_enabled = false

[main_window]
position = [594, 161]
size = [716, 457]
selected_page = 0

[log_view.columns]
2 = 50
1 = 500
6 = 50
8 = 50
0 = 300
3 = 50
5 = 50
7 = 50
4 = 50
