logging_enabled = false
layouts_enabled = false
layout = "game"

[main_window]
position = [822, 138]
size = [977, 560]
selected_page = 0

[log_view.columns]
8 = 50
6 = 108
0 = 187
4 = 50
5 = 50
7 = 94
1 = 179
2 = 89
3 = 50
