processing_enabled = true
logging_enabled = true
layouts_enabled = false
layout = "game"

[main_window]
position = [822, 138]
size = [977, 560]
selected_page = 0

[log_view.columns]
1 = 179
5 = 50
3 = 50
6 = 108
7 = 94
8 = 50
2 = 89
0 = 187
4 = 50
