processing_enabled = true
logging_enabled = true
layouts_enabled = false
layout = "invert_mouse"

[main_window]
position = [822, 138]
size = [977, 560]
selected_page = 0

[log_view.columns]
0 = 187
4 = 50
7 = 94
6 = 108
3 = 50
8 = 50
1 = 179
5 = 50
2 = 89
