logging_enabled = true
profiles_enabled = true
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[main_window]
position = [335, 147]
size = [1364, 428]
selected_page = 1

[main_window.log_view.columns]
6 = 64
4 = 73
8 = 50
0 = 300
2 = 77
5 = 81
3 = 79
1 = 500
7 = 50
