logging_enabled = true
profiles_enabled = true
transform_layout = "default"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[main_window]
position = [335, 147]
size = [1364, 428]
selected_page = 0

[main_window.log_view.columns]
4 = 73
0 = 300
3 = 79
8 = 50
2 = 77
1 = 500
5 = 81
6 = 64
7 = 50
