logging_enabled = true
profiles_enabled = true
transform_layout = "game"
toggle_layout_hot_key = "[] Zâ†‘"

[main_window]
position = [983, 147]
size = [716, 428]
selected_page = 1

[main_window.log_view.columns]
6 = 50
3 = 50
8 = 50
2 = 50
7 = 50
5 = 50
0 = 300
1 = 500
4 = 50
