processing_enabled = false
logging_enabled = true
layouts_enabled = true
layout = "default"

[main_window]
position = [1320, 41]
size = [716, 567]
selected_page = 0

[profiles.chrome]
rule = "Chrome"
layout = "game"
