processing_enabled = false
logging_enabled = false
layouts_enabled = true
layout = "default"

[main_window]
position = [1308, 143]
size = [716, 519]
selected_page = 0

[[profiles]]
name = "chrome"
rule = "Chrome"
layout = "game"
