logging_enabled = true
profiles_enabled = false

[main_window]
position = [1059, 184]
size = [716, 457]
selected_page = 0

[log_view.columns]
5 = 50
7 = 50
8 = 50
3 = 50
4 = 50
0 = 300
6 = 50
1 = 500
2 = 50
