processing_enabled = false
logging_enabled = false
layouts_enabled = false
layout = "invert_mouse"

[main_window]
position = [300, 300]
size = [716, 339]
selected_page = 0

[profiles.totalcmd]
rule = "TOTALCMD64.EXE"
layout = "game"

[profiles.chrome]
rule = "Chrome"
layout = "game"
