processing_enabled = true
logging_enabled = false
layouts_enabled = false
layout = "game"

[main_window]
position = [822, 138]
size = [977, 560]
selected_page = 0

[log_view.columns]
5 = 50
3 = 50
7 = 94
8 = 50
2 = 89
6 = 108
0 = 187
4 = 50
1 = 179
