logging_enabled = false
layouts_enabled = false

[main_window]
position = [822, 138]
size = [977, 560]
selected_page = 1

[log_view.columns]
3 = 50
2 = 89
1 = 179
8 = 50
4 = 50
7 = 94
0 = 187
6 = 108
5 = 50
