keys_logging_enabled = true
last_transform_layout = "game"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[layout_autoswitch]
enabled = true

[layout_autoswitch.profiles.chrome]
activation_rule = "Chrome"
layout = "desktop"

[layout_autoswitch.profiles.tc]
activation_rule = "TOTALCMD64.EXE"
layout = "game"

[main_window]
position = [300, 300]
size = [716, 339]
selected_page = 0

[main_window.log_view.columns]
2 = 50
0 = 300
5 = 50
7 = 50
4 = 50
8 = 50
1 = 500
3 = 50
6 = 50
