logging_enabled = true
profiles_enabled = true
transform_layout = "game"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[main_window]
position = [571, 286]
size = [1364, 428]
selected_page = 0

[main_window.log_view.columns]
1 = 500
0 = 300
2 = 77
7 = 50
3 = 79
4 = 73
8 = 50
5 = 81
6 = 64
