logging_enabled = true
profiles_enabled = true
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[main_window]
position = [608, 232]
size = [716, 428]
selected_page = 0

[main_window.log_view.columns]
2 = 50
3 = 50
5 = 50
1 = 500
6 = 50
8 = 50
0 = 300
7 = 50
4 = 50
