processing_enabled = true
logging_enabled = true
layouts_enabled = false
layout = "game"

[main_window]
position = [967, 200]
size = [716, 339]
selected_page = 0

[profiles.chrome]
rule = "Chrome"
layout = "game"

[profiles.totalcmd]
rule = "TOTALCMD64.EXE"
layout = "game"
