logging_enabled = true
profiles_enabled = true
transform_layout = "game"
toggle_layout_hot_key = "[] FN_LAUNCH_APP2â†‘"

[main_window]
position = [983, 147]
size = [716, 428]
selected_page = 0

[main_window.log_view.columns]
1 = 500
2 = 50
3 = 50
5 = 50
6 = 50
7 = 50
4 = 50
8 = 50
0 = 300
