processing_enabled = true
logging_enabled = false
layouts_enabled = true
layout = "default"

[main_window]
position = [1172, 185]
size = [716, 550]
selected_page = 0

[[profiles]]
name = "chrome"
rule = "Chrome"
layout = "game"
